# Generated by Django 4.1.6 on 2023-02-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price_rub_cod',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price_usd_cod',
        ),
        migrations.AlterField(
            model_name='item',
            name='price_rub',
            field=models.DecimalField(decimal_places=2, help_text='Пример: 1234,99', max_digits=10, verbose_name='Цена в рублях'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, help_text='Пример: 1234,99', max_digits=10, verbose_name='Цена в долларах'),
        ),
    ]
